name: Angular CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: 165.227.102.141
        username: root
        password: ${{secrets.CLAVESSH}}
        script: |
          cd /var/www/html/api
          git pull
          php artisan migrate
