name: Angular CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 209.38.31.107
          username: ${{secrets.USER}}
          password: ${{secrets.CLAVESSH}}
          script: |
            cd /var/www/html/api
            git pull
            composer inatall
            php artisan cache:clear
             #php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan migrate
            # php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"
            # php artisan jwt:secret
            # php artisan vendor:publish --provider="Laravel\Sanctum\SanctumServiceProvider"
